app = "pycon-tw-2025"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  FLET_SESSION_TIMEOUT = "60"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  
  [http_service.concurrency]
    type = "connections"
    soft_limit = 200
    hard_limit = 250